import Foundation

@main
struct GitaLogicTests {
    static func main() {
        precondition(UkuleleTuning.allCases.count == 3, "The supported four-string layouts must be explicit")
        precondition(UkuleleTuning.highG.openStrings.map(\.frequency) == [392, 261.63, 329.63, 440], "High-G targets must match open strings")
        precondition(UkuleleTuning.lowG.openStrings.map(\.frequency) == [196, 261.63, 329.63, 440], "Low-G must use G3 rather than G4")
        precondition(UkuleleTuning.baritone.openStrings.map(\.frequency) == [146.83, 196, 246.94, 329.63], "Baritone must use DGBE")
        precondition(Instrument.ukulele.tuningTargets(nil).isEmpty, "Unknown ukulele tuning must not assume high-G")
        precondition(Instrument.ukulele.tuningDisplayLabels(nil) == ["G", "C", "E", "A"], "Show familiar string names before the ukulele octave is identified")
        precondition(Instrument.ukulele.tuningDisplayLabels(.baritone) == ["D", "G", "B", "E"], "Update visible string names after baritone is identified")
        precondition(Instrument.guitar.tuningDisplayLabels(nil) == ["E", "A", "D", "G", "B", "E"], "Keep guitar labels unchanged")
        precondition(Instrument.guitar.tuningTargets(nil).count == 6, "Guitar targets must remain available")
        precondition(UkuleleTuning.lowG.lessons[2].frequencies.contains(196), "Low-G chord lesson must expect G3")
        precondition(UkuleleTuning.baritone.lessons[2].frequencies == [146.83, 196, 246.94, 392], "Baritone G chord target must match its strings")
        precondition(Instrument.ukulele.subtitle == "4 strings · automatic tuning", "Instrument choice must not promise high-G only")
        precondition(SetupProgress(instrument: .ukulele, tutorialComplete: false, completedTuning: [0, 1, 2, 3]).destination == .tuning, "Four checks without a layout cannot start the ukulele tutorial")
        precondition(SetupProgress(instrument: .ukulele, tutorialComplete: false, completedTuning: [0, 1, 2, 3], ukuleleTuning: .lowG).destination == .tutorial, "Four checks with a layout can start the tutorial")
        precondition(Instrument.ukulele.lessonTargets(.baritone)[0].frequencies == [329.63], "Baritone tutorial starts on open E")
        precondition(Instrument.ukulele.tuningTargets(.highG).map(\.label) == ["G", "C", "E", "A"], "Ukulele order must match the screen")
        precondition(abs(Instrument.guitar.tuningTargets(nil)[0].frequency - 82.4069) < 0.02, "Low E must be E2")
        precondition(Instrument.ukulele.lessonTargets(.highG).count == 3, "Ukulele has three guided exercises")
        precondition(Instrument.guitar.lessonTargets(nil).count == 3, "Guitar has three guided exercises")
        precondition(SetupProgress(instrument: nil, tutorialComplete: false).destination == .instrumentChoice)
        precondition(SetupProgress(instrument: .ukulele, tutorialComplete: false).destination == .tuning)
        precondition(SetupProgress(instrument: .ukulele, tutorialComplete: true).destination == .ready)
        let legacyPartial = Data(#"{"instrument":"ukulele","tutorialComplete":false,"completedTuning":[0,1],"lessonStep":0}"#.utf8)
        let migratedPartial = try! JSONDecoder().decode(SetupProgress.self, from: legacyPartial)
        precondition(migratedPartial.ukuleleTuning == nil && migratedPartial.completedTuning.isEmpty, "Legacy partial high-G checks must not be mistaken for an inferred layout")
        let legacyTutorial = Data(#"{"instrument":"ukulele","tutorialComplete":false,"completedTuning":[0,1,2,3],"lessonStep":2}"#.utf8)
        let migratedTutorial = try! JSONDecoder().decode(SetupProgress.self, from: legacyTutorial)
        precondition(migratedTutorial.ukuleleTuning == .highG && migratedTutorial.destination == .tutorial, "Legacy tutorial progress must retain high-G lessons")
        let legacyComplete = Data(#"{"instrument":"ukulele","tutorialComplete":true,"completedTuning":[0,1,2,3],"lessonStep":3}"#.utf8)
        let migratedComplete = try! JSONDecoder().decode(SetupProgress.self, from: legacyComplete)
        precondition(migratedComplete.ukuleleTuning == .highG && migratedComplete.destination == .ready, "Finished legacy onboarding must remain finished")
        let newUnknown = SetupProgress(instrument: .ukulele, tutorialComplete: false)
        let decodedNewUnknown = try! JSONDecoder().decode(SetupProgress.self, from: JSONEncoder().encode(newUnknown))
        precondition(decodedNewUnknown.ukuleleTuning == nil && decodedNewUnknown.destination == .tuning, "New nil profile must survive encoding")
        var retuned = SetupProgress(instrument: .ukulele, tutorialComplete: true, completedTuning: [0, 1, 2, 3], ukuleleTuning: .lowG)
        retuned.resetTuning()
        precondition(retuned.instrument == .ukulele && retuned.ukuleleTuning == nil && retuned.completedTuning.isEmpty, "Retune must clear checks and inferred layout only")
        let sampleRate = 44_100.0
        precondition(PitchDetector.gOctaveEvidence(tone(392, count: 8_192, sampleRate: sampleRate), sampleRate: sampleRate, estimatedFrequency: 392) == .high, "Pure high G must not be classified as low G")
        precondition(PitchDetector.gOctaveEvidence(harmonicTone(196, lowAmplitude: 0.35, highAmplitude: 1, count: 8_192, sampleRate: sampleRate), sampleRate: sampleRate, estimatedFrequency: 392) == .low, "Low G with a loud octave harmonic must retain its fundamental")
        precondition(PitchDetector.gOctaveEvidence(harmonicTone(196, lowAmplitude: 0.15, highAmplitude: 1, count: 8_192, sampleRate: sampleRate), sampleRate: sampleRate, estimatedFrequency: 392) == .uncertain, "Weak fundamental must remain ambiguous")
        let a4 = tone(440, count: 8_192, sampleRate: sampleRate)
        let estimate = PitchDetector.estimate(a4, sampleRate: sampleRate)
        precondition(estimate != nil && abs(estimate!.frequency - 440) < 3, "A4 estimate must be close to 440 Hz")
        precondition(PitchDetector.estimate(Array(repeating: 0, count: 8_192), sampleRate: sampleRate) == nil, "Silence must not be a note")
        precondition(abs(PitchDetector.cents(440, target: 440)) < 0.1)
        precondition(abs(PitchDetector.cents(466.16, target: 440) - 100) < 0.5)
        let lowE = tone(82.4069, count: 8_192, sampleRate: sampleRate)
        precondition(abs((PitchDetector.estimate(lowE, sampleRate: sampleRate)?.frequency ?? 0) - 82.4069) < 2, "Low guitar E2 must be detected")
        let cChord = mixture([261.63, 329.63, 392, 523.25], count: 8_192, sampleRate: sampleRate)
        let chordPitch = PitchDetector.estimate(cChord, sampleRate: sampleRate)
        precondition(chordPitch == nil || chordPitch!.clarity < 0.84, "A multi-note strum must not count as a clear single pitch")
        precondition(ChordMatcher.matches(cChord, sampleRate: sampleRate, targets: [261.63, 329.63, 392, 523.25]), "C chord pitch content should match")
        precondition(!ChordMatcher.matches(a4, sampleRate: sampleRate, targets: [261.63, 329.63, 392, 523.25]), "A single pitch is not a C chord")
        precondition(!ChordMatcher.matches(Array(repeating: 0, count: 8_192), sampleRate: sampleRate, targets: [261.63, 329.63, 392, 523.25]), "Silence is not a chord")
        let suite = "GitaLogicTests.\(UUID().uuidString)"
        guard let isolatedDefaults = UserDefaults(suiteName: suite) else { fatalError("Unable to make isolated defaults") }
        let progressStore = ProgressStore(defaults: isolatedDefaults)
        progressStore.save(SetupProgress(instrument: .ukulele, tutorialComplete: true), for: "account-A")
        precondition(progressStore.load(for: "account-A").destination == .ready)
        precondition(progressStore.load(for: "account-B").destination == .instrumentChoice, "Progress must not cross Apple accounts")
        progressStore.saveGuest(SetupProgress(instrument: .guitar, tutorialComplete: true))
        precondition(progressStore.loadGuest().instrument == .guitar, "Guest progress stays in its own slot")
        precondition(progressStore.load(for: "account-A").instrument == .ukulele, "Guest must not replace Apple progress")
        progressStore.setGuestModeEnabled(true)
        precondition(ProgressStore(defaults: isolatedDefaults).isGuestModeEnabled, "Guest choice persists across launches")
        precondition(SetupPolicy.route(guestMode: true, userID: nil, progress: progressStore.loadGuest(), started: false) == .ready, "Returning guest resumes progress")
        progressStore.setGuestModeEnabled(false)
        precondition(!ProgressStore(defaults: isolatedDefaults).isGuestModeEnabled, "Switching to Apple leaves guest mode")
        precondition(progressStore.loadGuest().destination == .ready, "Leaving guest mode does not erase guest practice")
        progressStore.saveGuest(SetupProgress(instrument: .ukulele, tutorialComplete: true, ukuleleTuning: .lowG))
        progressStore.save(SetupProgress(instrument: .ukulele, tutorialComplete: true, ukuleleTuning: .baritone), for: "account-A")
        precondition(progressStore.loadGuest().ukuleleTuning == .lowG && progressStore.load(for: "account-A").ukuleleTuning == .baritone, "Guest and Apple accounts must retain separate ukulele layouts")
        isolatedDefaults.removePersistentDomain(forName: suite)
        var judge = TuningJudge()
        precondition(!judge.ingest(PitchReading(frequency: 440, clarity: 0.95), target: 440, at: 0.0))
        precondition(!judge.ingest(PitchReading(frequency: 440, clarity: 0.95), target: 440, at: 0.25))
        precondition(judge.ingest(PitchReading(frequency: 440, clarity: 0.95), target: 440, at: 0.55), "Stable half-second in tune should complete")
        judge.reset()
        precondition(!judge.ingest(PitchReading(frequency: 440, clarity: 0.95), target: 440, at: 1.0))
        precondition(!judge.ingest(nil, target: 440, at: 1.4))
        precondition(!judge.ingest(PitchReading(frequency: 466.16, clarity: 0.95), target: 440, at: 1.8), "Wrong pitch must not complete")
        precondition(TuningZone.classify(nil) == .waiting, "Silence must not show a tuning direction")
        precondition(TuningZone.classify(8) == .inTune, "A small offset should be in tune")
        precondition(TuningZone.classify(-18) == .closeFlat, "A near-flat note should show close, not too low")
        precondition(TuningZone.classify(15) == .closeSharp, "A near-sharp note should show close, not too high")
        precondition(TuningZone.classify(25) == .sharp, "A larger offset should remain too high")
        judge.reset()
        precondition(!judge.ingest(PitchReading(frequency: 443.8, clarity: 0.95), target: 440, at: 2.0))
        precondition(!judge.ingest(PitchReading(frequency: 443.8, clarity: 0.95), target: 440, at: 2.6), "A close note must not auto-complete outside the true in-tune window")
        precondition(SetupPolicy.route(userID: nil, progress: SetupProgress(), started: false) == .welcome)
        precondition(SetupPolicy.route(userID: nil, progress: SetupProgress(), started: true) == .signIn)
        precondition(SetupPolicy.route(userID: "account-A", progress: SetupProgress(instrument: .guitar, tutorialComplete: true), started: false) == .ready)
        precondition(SetupRoute.tuning.usesMicrophone && SetupRoute.tutorial.usesMicrophone)
        precondition(!SetupRoute.signIn.usesMicrophone && !SetupRoute.ready.usesMicrophone)
        var autoTuner = AutoTuner()
        let ukuleleStrings = Instrument.ukulele.tuningTargets(.highG)
        let cFeedback = autoTuner.ingest(PitchReading(frequency: 261.63, clarity: 0.95), targets: ukuleleStrings, at: 0)
        precondition(cFeedback.stringIndex == 1 && abs(cFeedback.cents ?? 1_000) < 1, "Open C should be selected without a tap")
        precondition(cFeedback.newlyTunedIndex == nil, "One reading must not finish a string")
        let cTuned = autoTuner.ingest(PitchReading(frequency: 261.63, clarity: 0.95), targets: ukuleleStrings, at: 0.6)
        precondition(cTuned.newlyTunedIndex == 1, "A steady open C should complete automatically")
        let sharpA = autoTuner.ingest(PitchReading(frequency: 450, clarity: 0.95), targets: ukuleleStrings, at: 1)
        precondition(sharpA.stringIndex == 3 && (sharpA.cents ?? 0) > 0, "The A indicator should move toward sharp")
        precondition(sharpA.newlyTunedIndex == nil, "Switching strings resets tuning stability")
        let weakReading = autoTuner.ingest(PitchReading(frequency: 440, clarity: 0.2), targets: ukuleleStrings, at: 1.1)
        precondition(weakReading.stringIndex == nil, "Noisy audio must not guess a string")
        let distantReading = autoTuner.ingest(PitchReading(frequency: 493.88, clarity: 0.95), targets: ukuleleStrings, at: 1.2)
        precondition(distantReading.stringIndex == nil, "A note far from open tuning must not pick the nearest string")
        let highE = autoTuner.ingest(PitchReading(frequency: 329.63, clarity: 0.95), targets: Instrument.guitar.tuningTargets(nil), at: 2)
        precondition(highE.stringIndex == 5, "The guitar high E should not be confused with its low E")
        precondition(autoTuner.ingest(nil, targets: Instrument.guitar.tuningTargets(nil), at: 2.2).stringIndex == nil, "Silence clears the live string indication")

        var highGAuto = UkuleleAutoTuner()
        let firstHigh = pluck(&highGAuto, hz: 392, gEvidence: .high, at: 1)
        precondition(firstHigh.confirmedTuning == nil && firstHigh.completed.isEmpty, "One pluck must not choose a layout or physical string")
        let lockedHigh = pluck(&highGAuto, hz: 261.63, at: 2)
        precondition(lockedHigh.confirmedTuning == .highG && lockedHigh.completed == [0, 1], "Distinct G4 and C4 plucks should identify and check high-G")
        _ = pluck(&highGAuto, hz: 329.63, at: 3)
        let finishedHigh = pluck(&highGAuto, hz: 440, at: 4)
        precondition(finishedHigh.completed == [0, 1, 2, 3], "Each high-G string should be checked without taps")
        precondition(finishedHigh.finishedNow, "The fourth newly checked string should trigger completion")
        var reopenedTuner = UkuleleAutoTuner(confirmedTuning: .highG, completed: [0, 1, 2, 3])
        let reopenedReading = reopenedTuner.ingest(PitchReading(frequency: 440, clarity: 0.95), gEvidence: nil, at: 0)
        precondition(!reopenedReading.finishedNow, "Returning to a completed tuner must not auto-advance again")

        var lowGAuto = UkuleleAutoTuner()
        _ = pluck(&lowGAuto, hz: 440, at: 1)
        let lockedLow = pluck(&lowGAuto, hz: 196, gEvidence: .low, at: 2)
        precondition(lockedLow.confirmedTuning == .lowG && lockedLow.completed == [0, 3], "A4 and G3 should identify low-G regardless of order")
        _ = pluck(&lowGAuto, hz: 261.63, at: 3)
        let finishedLow = pluck(&lowGAuto, hz: 329.63, at: 4)
        precondition(finishedLow.completed == [0, 1, 2, 3], "All low-G strings should complete")

        var baritoneAuto = UkuleleAutoTuner()
        _ = pluck(&baritoneAuto, hz: 246.94, at: 1)
        let lockedBaritone = pluck(&baritoneAuto, hz: 146.83, at: 2)
        precondition(lockedBaritone.confirmedTuning == .baritone && lockedBaritone.completed == [0, 2], "B3 and D3 should identify baritone")
        _ = pluck(&baritoneAuto, hz: 196, gEvidence: .low, at: 3)
        let finishedBaritone = pluck(&baritoneAuto, hz: 329.63, at: 4)
        precondition(finishedBaritone.completed == [0, 1, 2, 3], "All baritone strings should complete")

        var sharedNotes = UkuleleAutoTuner()
        _ = pluck(&sharedNotes, hz: 329.63, at: 1)
        let sharedG = pluck(&sharedNotes, hz: 196, gEvidence: .low, at: 2)
        precondition(sharedG.confirmedTuning == nil && sharedG.completed.isEmpty && sharedG.needsTopStringPrompt, "E4 and G3 cannot establish a physical layout")
        var repeatedNote = UkuleleAutoTuner()
        _ = pluck(&repeatedNote, hz: 440, at: 1)
        let repeatedResult = pluck(&repeatedNote, hz: 440, at: 2)
        precondition(repeatedResult.confirmedTuning == nil, "Repeated A4 must count as one distinct target")
        var ambiguousG = UkuleleAutoTuner()
        let unresolved = pluck(&ambiguousG, hz: 392, gEvidence: .uncertain, at: 1)
        precondition(unresolved.completed.isEmpty && unresolved.confirmedTuning == nil && unresolved.needsTopStringPrompt, "Harmonic-conflicted G must not create a check")
        var swingingG = UkuleleAutoTuner(confirmedTuning: .highG)
        _ = swingingG.ingest(PitchReading(frequency: 392, clarity: 0.95), gEvidence: .high, at: 0)
        _ = swingingG.ingest(PitchReading(frequency: 392, clarity: 0.95), gEvidence: .high, at: 0.18)
        let oneUncertainG = swingingG.ingest(PitchReading(frequency: 392, clarity: 0.95), gEvidence: .uncertain, at: 0.25)
        precondition(oneUncertainG.stringIndex == 0 && oneUncertainG.cents != nil && oneUncertainG.newlyTuned.isEmpty, "One uncertain G frame should hold the last needle position without granting a check")
        let repeatedUncertainG = swingingG.ingest(PitchReading(frequency: 392, clarity: 0.95), gEvidence: .uncertain, at: 0.55)
        precondition(repeatedUncertainG.status == .ambiguous && repeatedUncertainG.cents == nil, "A sustained uncertain G must stop showing a confident pitch")
        var intermittentG = UkuleleAutoTuner(confirmedTuning: .highG)
        _ = intermittentG.ingest(PitchReading(frequency: 392, clarity: 0.95), gEvidence: .high, at: 0)
        _ = intermittentG.ingest(PitchReading(frequency: 392, clarity: 0.95), gEvidence: .high, at: 0.18)
        _ = intermittentG.ingest(PitchReading(frequency: 392, clarity: 0.95), gEvidence: .uncertain, at: 0.36)
        _ = intermittentG.ingest(PitchReading(frequency: 392, clarity: 0.95), gEvidence: .high, at: 0.54)
        _ = intermittentG.ingest(PitchReading(frequency: 392, clarity: 0.95), gEvidence: .uncertain, at: 0.72)
        _ = intermittentG.ingest(PitchReading(frequency: 392, clarity: 0.95), gEvidence: .high, at: 0.90)
        _ = intermittentG.ingest(PitchReading(frequency: 392, clarity: 0.95), gEvidence: .uncertain, at: 1.08)
        let recoveredG = intermittentG.ingest(PitchReading(frequency: 392, clarity: 0.95), gEvidence: .high, at: 1.26)
        precondition(recoveredG.completed.contains(0), "Intermittent one-frame G uncertainty must not prevent a check forever")
        var harmonicG = UkuleleAutoTuner()
        _ = pluck(&harmonicG, hz: 392, gEvidence: .low, at: 1)
        let harmonicLocked = pluck(&harmonicG, hz: 440, at: 2)
        precondition(harmonicLocked.confirmedTuning == .lowG && harmonicLocked.completed == [0, 3], "A G4 harmonic identified as low G must map to G3")

        var noisy = UkuleleAutoTuner()
        let noisyReading = noisy.ingest(PitchReading(frequency: 440, clarity: 0.2), gEvidence: nil, at: 0)
        precondition(noisyReading.completed.isEmpty && noisyReading.confirmedTuning == nil, "Weak audio must not count")
        let chordReading = PitchDetector.estimate(cChord, sampleRate: sampleRate)
        let chordInput: PitchReading? = (chordReading?.clarity ?? 0) < 0.84 ? nil : chordReading
        precondition(noisy.ingest(chordInput, gEvidence: nil, at: 0.2).completed.isEmpty, "A strum must not check an individual string")
        precondition(noisy.ingest(PitchReading(frequency: 600, clarity: 0.95), gEvidence: nil, at: 0.4).completed.isEmpty, "Distant notes must not check a string")

        var closeOnly = UkuleleAutoTuner(confirmedTuning: .highG)
        let fifteenCentsSharp = 440 * pow(2, 15.0 / 1_200)
        let closeResult = pluck(&closeOnly, hz: fifteenCentsSharp, at: 1)
        precondition(closeResult.completed.isEmpty && closeResult.cents != nil && closeResult.cents! > 10, "Close guidance must not be a green check")

        var dropout = UkuleleAutoTuner(confirmedTuning: .highG)
        _ = dropout.ingest(PitchReading(frequency: 440, clarity: 0.95), gEvidence: nil, at: 10)
        _ = dropout.ingest(PitchReading(frequency: 440, clarity: 0.95), gEvidence: nil, at: 10.18)
        _ = dropout.ingest(nil, gEvidence: nil, at: 10.30)
        _ = dropout.ingest(PitchReading(frequency: 440, clarity: 0.95), gEvidence: nil, at: 10.40)
        _ = dropout.ingest(PitchReading(frequency: 440, clarity: 0.95), gEvidence: nil, at: 10.58)
        let afterDropout = dropout.ingest(PitchReading(frequency: 440, clarity: 0.95), gEvidence: nil, at: 10.75)
        precondition(afterDropout.completed.contains(3), "A brief missing frame should not erase valid tuning time")

        var lessonJudge = LessonJudge()
        precondition(!lessonJudge.matches(a4, sampleRate: sampleRate, target: Instrument.guitar.lessonTargets(nil)[0]), "A4 is not the guitar high E")
        lessonJudge.reset()
        precondition(lessonJudge.matches(tone(329.63, count: 8_192, sampleRate: sampleRate), sampleRate: sampleRate, target: Instrument.guitar.lessonTargets(nil)[0]), "High E pluck should match")
        lessonJudge.reset()
        precondition(!lessonJudge.matches(a4, sampleRate: sampleRate, target: Instrument.ukulele.lessonTargets(.highG)[2]), "One note cannot pass a chord lesson")
        lessonJudge.reset()
        precondition(lessonJudge.matches(cChord, sampleRate: sampleRate, target: Instrument.ukulele.lessonTargets(.highG)[2]), "Chord content with an attack should pass")
        lessonJudge.reset()
        lessonJudge.observe(cChord)
        precondition(!lessonJudge.matches(cChord, sampleRate: sampleRate, target: Instrument.ukulele.lessonTargets(.highG)[2]), "A chord held before the cue is not a new strum")
        lessonJudge.observe(Array(repeating: 0, count: 8_192))
        precondition(lessonJudge.matches(cChord, sampleRate: sampleRate, target: Instrument.ukulele.lessonTargets(.highG)[2]), "A fresh strum after silence is accepted")
        var lowGJudge = LessonJudge()
        let lowGChord = mixture([261.63, 329.63, 196, 523.25], count: 8_192, sampleRate: sampleRate)
        precondition(lowGJudge.matches(lowGChord, sampleRate: sampleRate, target: Instrument.ukulele.lessonTargets(.lowG)[2]), "Low-G tutorial chord should match its actual low G")
        var baritoneJudge = LessonJudge()
        let baritoneChord = mixture([146.83, 196, 246.94, 392], count: 8_192, sampleRate: sampleRate)
        precondition(baritoneJudge.matches(baritoneChord, sampleRate: sampleRate, target: Instrument.ukulele.lessonTargets(.baritone)[2]), "Baritone G chord should match DGBE with E-string fret 3")
        print("Gita logic tests passed")
    }

    private static func tone(_ frequency: Double, count: Int, sampleRate: Double) -> [Float] {
        (0..<count).map { Float(sin(2 * Double.pi * frequency * Double($0) / sampleRate)) }
    }

    private static func mixture(_ frequencies: [Double], count: Int, sampleRate: Double) -> [Float] {
        (0..<count).map { index in
            Float(frequencies.reduce(0) { sum, frequency in
                sum + sin(2 * Double.pi * frequency * Double(index) / sampleRate)
            } / Double(frequencies.count))
        }
    }

    private static func harmonicTone(_ base: Double, lowAmplitude: Double, highAmplitude: Double, count: Int, sampleRate: Double) -> [Float] {
        (0..<count).map { index in
            let phase = 2 * Double.pi * Double(index) / sampleRate
            return Float((lowAmplitude * sin(base * phase) + highAmplitude * sin(2 * base * phase)) / (lowAmplitude + highAmplitude))
        }
    }

    private static func pluck(_ tuner: inout UkuleleAutoTuner, hz: Double, gEvidence: GOctaveEvidence? = nil, at start: Double) -> UkuleleTunerFeedback {
        var result = tuner.ingest(nil, gEvidence: nil, at: start - 0.05)
        for offset in [0.0, 0.18, 0.36, 0.54] {
            result = tuner.ingest(PitchReading(frequency: hz, clarity: 0.95), gEvidence: gEvidence, at: start + offset)
        }
        _ = tuner.ingest(nil, gEvidence: nil, at: start + 0.59)
        return result
    }
}
